### ISSUE TITLE
./libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'

### ISSUE THREAD

**Issue by frankplow** [ffvvc/FFmpeg#116]
A recent update to binutils has broken FFmpeg compilation: https://trac.ffmpeg.org/ticket/10405. There is a [fix in FFmpeg master](https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/effadce6c756247ea8bae32dc13bb3e6f464f0eb), so we will need to merge/rebase to allow building with binutils >= 2.41.

**Comment by nuomi2021** [comment]
@frankplow , thank you for reporting this. I am working on using cbs to decoder parameter set. after it, we will rebased to latest ffmepg code

**Comment by nuomi2021** [comment]
@frankplow , will freeze and rename the current main branch. and use https://github.com/ffvvc/FFmpeg/pull/118 instead.

thank you

**Comment by frankplow** [comment]
@nuomi2021 #118 Does the trick for me 👍

**Comment by nuomi2021** [comment]
branch switched https://github.com/ffvvc/FFmpeg
