### ISSUE TITLE
prefix TxType and TxSize with VVC. 

### ISSUE THREAD

**Issue by nuomi2021** [ffvvc/FFmpeg#180]
see discussion at https://patchwork.ffmpeg.org/project/ffmpeg/patch/TYSPR06MB64337C4A9ADF5312E6648543AA62A@TYSPR06MB6433.apcprd06.prod.outlook.com/#81892

**Comment by QSXW** [comment]
See https://github.com/ffvvc/FFmpeg/pull/251

**Comment by QSXW** [comment]
The change is merged into upstream and close this issue now.
