### ISSUE TITLE
LMCS_B_Dolby Failure

### ISSUE THREAD

**Issue by frankplow** [ffvvc/FFmpeg#189]
The conformance bitstream LMCS_B_Dolby is currently failing.  At the moment, this is due to an AVERROR_INVALIDDATA.  This can be resolved with this patch: https://patchwork.ffmpeg.org/project/ffmpeg/patch/20240126162043.59687-1-post@frankplowman.com/

Even with that patch applied however, the test still fails.  YUView shows the first frames are identical, but all subsequent frames differ.  Together with the visual nature of the distortions, inter prediction looks suspect.

**Comment by nuomi2021** [comment]
the file is a subpic file. I checked spec, subpic may be a little hard for gsoc, I will try to pick up your https://github.com/ffvvc/FFmpeg/pull/191 and work on it.

**Comment by frankplow** [comment]
@nuomi2021 Yes I worked this is due to subpics also, sorry should have posted here.  I think #191 is all the derivations etc. for `pps_single_slice_per_subpic_flag`/`pps_rect_slice_flag`.  I think the errors in #191 as it stands are the same errors we see in LMCS_B_Dolby and the other subpic bitstreams and are because we don't handle `sps_independent_subpics_flag`.  Unfortunately it doesn't seem there are any test bitstreams with `pps_single_slice_per_subpic_flag=1` and `sps_independent_subpics_flag=0`, so it is difficult to test seperately.

**Comment by nuomi2021** [comment]
fixed by https://github.com/FFmpeg/FFmpeg/commit/238bb653e7ea466a024d027072b57d0a9a1278d7, thank you @frankplow
