### ISSUE TITLE
use tb->max_scan_x  and tb->max_scan_y to optimze dct8 and dst7

### ISSUE THREAD

**Issue by nuomi2021** [ffvvc/FFmpeg#20]
by the nature of transformation, We only have a few no zero coeffes. the position is recorded by  tb->max_scan_x  and tb->max_scan_y.

We can use this to optimize 
https://github.com/ffvvc/FFmpeg/blob/3cb136dc5fc70d65f9918453a842439323e81908/libavcodec/vvc_itx_1d.c#L146

see https://vcgit.hhi.fraunhofer.de/jvet/VVCSoftware_VTM/-/blob/master/source/Lib/CommonLib/TrQuant_EMT.cpp#L886 for reference.

**Comment by DataCrusade1999** [comment]
Hi @nuomi2021, My name is Ashutosh Pandey and I would like to take this issue up as my qualification task for this year's GSoC any advice on how should I set up my development environment for this task? I'm on a Windows machine and I also have WSL enabled.

**Comment by nuomi2021** [comment]
Hi @DataCrusade1999 , glad you are willing to do this. 
Please go ahead. 
thank you

**Comment by DataCrusade1999** [comment]
Thanks for responding, So I followed the instaruvtions given in `makefile.yml` and succesfully built ffmpeg with few warnings I also ran tests as specified in the `makefile.yml` and all tests passed except these 6

`+++++++++ report +++++++++`
`failed files:`
    `MERGE_I_Qualcomm_2.bit`
    `MERGE_J_Qualcomm_2.bit`
    `MERGE_H_Qualcomm_2.bit`
    `ENTROPY_A_Chipsnmedia_2.bit`
    `TREE_C_HHI_3.bit`
    `CUBEMAP_A_MediaTek_3.bit`

I'm using `gcc` to compile.
I also ran `gcc libavcodec/vvc_itx_1d.c` and got multiple undefined refrence errors to `dct8` ,`dst7` and `ff_vvc_lfnst_8x8` 

did you mean to say `dct2` or `dst2`? cause I used `git grep -e "dst2"` and there are lot of refrences but none that I could make sense of regarding this task. and if it is indeed `dct2` will the implmentation of `dst8` and `dst7` will be the same as `dct2` or a bit different and if you could please tell me what to look for in the reference then that would be great?

**Comment by nuomi2021** [comment]
> and all tests passed except these 6

Is it related to WSL? Could you help setup WSL ci(https://github.com/ffvvc/FFmpeg/issues/40)? 

> I also ran gcc libavcodec/vvc_itx_1d.c

Please use gdb ./ffmpeg_g to debug.  you can use bread at https://github.com/ffvvc/FFmpeg/blob/main/libavcodec/vvc_ctu.c#L1332 to see what happened

> did you mean to say dct2 or dst2?
There are 3 transform types in vvc: dct2, dct8, and dst 7. We do vector [multiply](https://github.com/ffvvc/FFmpeg/blob/3cb136dc5fc70d65f9918453a842439323e81908/libavcodec/vvc_itx_1d.c#L166) for dct8 and dst7.  Current we will multiple all inputs. but due to nature of codec. the input will be zero after max_scan_x + 1 and max_scan_y + 1, wo do not need do multiple for these element

**Comment by DataCrusade1999** [comment]
Thanks for the response I'll use `gdb` now to debug and lookup some more info about transform types in vvc. Thanks again

**Comment by hamzah-mujawar** [comment]
Hi,

Can I work on this issue, is anyone still working on this?

Thanks,
Hamzah Mujawar

**Comment by nuomi2021** [comment]
@hamzah-mujawar , yes you can work on this.

https://github.com/ffvvc/FFmpeg/issues/179 is related to this, please consider it too.
thank you

**Comment by hamzah-mujawar** [comment]
Progress Update:

After building ffmpeg, I've been able to debug and set a breakpoint on line number: 88 in vvc_itx_1d.c:
![image](https://github.com/ffvvc/FFmpeg/assets/16957086/ad9ad259-c6da-498d-b814-422bbd80100f)
I tried to debug this using gdb here are my steps:
1) Ran gdb ./ffmpeg_g
2) Set a breakpoint using vvc_itx_1d.c on line 88
3) Ran ffmpeg using the run command
I have attached a screenshot below of these steps:
![image](https://github.com/ffvvc/FFmpeg/assets/16957086/1c35583a-7c22-459b-b870-99697a1cf0f4)

I would like to ask, what prompt(format: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile) can I use to check the program so I can see what is done for dct2?

Also, am I approaching this the right way?

Thanking you for your time,
Hamzah Mujawar

**Comment by nuomi2021** [comment]
@hamzah-mujawar，you can check our workflow https://github.com/ffvvc/FFmpeg/blob/main/.github/workflows/makefile.yml
it will download test clips and test it. most clips has dct2, you can choose a small one

**Comment by hamzah-mujawar** [comment]
Hi,

I have some trouble running the workflow:
![image](https://github.com/ffvvc/FFmpeg/assets/16957086/6fe0c4a7-745d-4188-8fcd-db9dfe23ce21)

Is this the right branch to run it on?

Thanking you for your time,
Hamzah Mujawar

**Comment by hamzah-mujawar** [comment]
Progress Update:

I finally am able to hit breakpoints on vvc_itx_1d.c :). 
![image](https://github.com/ffvvc/FFmpeg/assets/16957086/0d070e3f-78b9-4d6e-b83d-e52928d99d09)

I wasn't able to run the workflow, however I downloaded the tests repository, and ran the python3 script. I am now running this in gdb:  run  -i ~/tests/conformance/passed/v1/8b400_A_Bytedance_2.bit -vsync 0 -f md5 - in gdb.

I will continue down this rabbit hole and report back.

Thanking you for your time,
Hamzah Mujawar

**Comment by hamzah-mujawar** [comment]
Hi,

I have a rough solution for ff_vvc_inv_dct8_4:

```c
void ff_vvc_inv_dct8_4(int *coeffs, const ptrdiff_t stride, const size_t nz) {
  const int a = 64, b = 83, c = 36;
  const int x0 = coeffs[0 * stride], x1 = coeffs[1 * stride];
  const int x2 = coeffs[2 * stride], x3 = coeffs[3 * stride];

  const int C[4] = {
      (x0 + x3),
      (x2 + x0),
      (x3 - x2),
      (a * x1),
  };
  coeffs[0 * stride] = c * C[0] + b * C[1] + C[3];
  coeffs[1 * stride] = a * (x0 - x2 - x3);
  coeffs[2 * stride] = c * C[2] + b * C[0] - C[3];
  coeffs[3 * stride] = c * C[1] - b * C[2] - C[3];
}
```

This above code is adapted from your provided reference: https://vcgit.hhi.fraunhofer.de/jvet/VVCSoftware_VTM/-/blob/master/source/Lib/CommonLib/TrQuant_EMT.cpp#L886

I've made a few assumptions (which are probably wrong, and would love to get corrected by you if possible)
1) I've assumed iT[1].....iT[3] are a, b, c constants that are previously defined in ff_vvc_inv_dct2_2.
2) I've assumed src[0*line] ..... src[3*line] correspond to x0.... x3.
3) I've assumed the constants remain the same for DCT_8

This was a lot of fun trying to understand.


Thanking you for your time,
Hamzah Mujawar

**Comment by hamzah-mujawar** [comment]
Hi @nuomi2021 ,

I've written a rough solution for matrix_mult in vvc_itx_1d.c and have a few doubts regarding implementation that I would like getting cleared by you when you have the time.

```c
static void matrix_mul(int *coeffs, const ptrdiff_t stride,
                       const int8_t *matrix, const int size, const size_t nz,
                       TransformBlock *tb) {
  int outer_loop_bound = 0, inner_loop_bound = 0;
  // for dst7 and dct8, coeffs > 16 are zero out
  int tmp[16];

  for (int i = 0; i < nz; i++)
    tmp[i] = coeffs[i * stride];

  outer_loop_bound = FFMIN(tb->max_scan_x, size);

  for (int i = 0; i < outer_loop_bound; i++) {
    int o = 0;
    inner_loop_bound = FFMIN(tb->max_scan_y, nz);
    for (int j = 0; j < inner_loop_bound; j++)
      o += tmp[j] * matrix[j * size];
    *coeffs = o;
    coeffs += stride;
    matrix++;
  }
}
```

In this implementation, the function matrix_mul will take in the TransformBlock structure through which we should be able to access the tb->max integers which are defined in vvc_ctu.h which needs to be included as well in vvc_itx_1d.c.

I am confused however, as when I looked at vvc_cabac there we access the TransformBlock using the ResidualCoding Structure.

Am I heading in the right direction?

Thanking your time and guidance,
Hamzah Mujawar

**Comment by hamzah-mujawar** [comment]
Hi,

Could you please point me to the line of code that was shown here in this commit: https://github.com/ffvvc/FFmpeg/blob/main/libavcodec/vvc_ctu.c#L1332

Thanking you,
Hamzah Mujawar

**Comment by frankplow** [comment]
> Could you please point me to the line of code that was shown here in this commit: https://github.com/ffvvc/FFmpeg/blob/main/libavcodec/vvc_ctu.c#L1332

This file was moved to `libavcodec/vvc/vvc_ctu.c`:
https://github.com/ffvvc/FFmpeg/blob/e81b6d78fc2ddf8edd53a6a052713354ef8d27c2/libavcodec/vvc/vvc_ctu.c#L1332

**Comment by hamzah-mujawar** [comment]
Hi,

I've created a pdf document going over the findings and potential changes, and have attached it to this message.

Now that I am able to access tb->max_scan_x, I would appreciate some pointers on how I can use it to optimise matrix_mul.

[issue_20.pdf](https://github.com/ffvvc/FFmpeg/files/14468191/issue_20.pdf)

Thanking you,
Hamzah Mujawar

**Comment by nuomi2021** [comment]
Hi @hamzah-mujawar , 
Good progress.
We can only give you some hints on this. please:
1.  find which clip will use dct8 or dst7 (Hint: you can run our conformances test on local, and pick the smallest one)
2. break down at matrix_mul using gdb.
3. at the same time break down at VTM, forwardMatrixMult function
compare the value in 2 and 3,  see what is counterparts for "reducedLine" and "`numInLines`"

thank you.

**Comment by hamzah-mujawar** [comment]
Hi,

I've been able to do 1 and 2, I have compiled the VTM software. I've tried multiple approaches on trying to set a breakpoint on forwardMatrixMult function and even just printing out the values of reducedLine and numInLines, but I am not able to get any results.

I will try again tomorrow.

Thanking you,
Hamzah Mujawar

**Comment by nuomi2021** [comment]
> set a breakpoint on forwardMatrixMult function and even just printing out the values of reducedLine and numInLines, but I am not able to get any results.
you can run the same clip as 2, and add an assert(0) in forwardMatrixMult or his parent function.

**Comment by hamzah-mujawar** [comment]
Hi,

Sorry to trouble you again.

I'm really confused as I'm not able to hit the assert either, I have built it and ran all the apps show here:
![image](https://github.com/ffvvc/FFmpeg/assets/16957086/c79583ae-09c2-4640-a320-ed3622b40043)

I'm running this command: ./BitstreamExtractorAppStaticd -b ~/tests/conformance/passed/v1/8b400_A_Bytedance_2.bit.

I've checked the stack trace to confirm dst7 is being used on 8b400_A_Bytedance_2.bit:
![image](https://github.com/ffvvc/FFmpeg/assets/16957086/284ab6cc-da24-4284-b63e-b4cc187c9424)

I've read the documentation in /docs however I haven't found a solution.


Thanking you for your time,
Hamzah Mujawar

**Comment by nuomi2021** [comment]
please run it with "DecoderAppStaticd -b 8b400_A_Bytedance_2.bit --SIMD=SCALAR"
you may need to define JVET_M0497_MATRIX_MULT to 1 and set a breakpoint at fastInverseDST7_B32

**Comment by nuomi2021** [comment]
implemented https://github.com/ffvvc/FFmpeg/blob/e81b6d78fc2ddf8edd53a6a052713354ef8d27c2/libavcodec/vvc/vvc_itx_1d.c#L662

thank you all for help on this
