### ISSUE TITLE
CI: Create all crash and hang cases as failed.

### ISSUE THREAD

**Issue by nuomi2021** [ffvvc/FFmpeg#218]
Even if we can't decode the files in https://github.com/ffvvc/tests/tree/main/conformance/failed, crashing ffmpeg is still an issue.
Let us update https://github.com/ffvvc/FFmpeg/tree/workflow, capture all crash issues, and fix them.

**Comment by frankplow** [comment]
Done in https://github.com/ffvvc/tests/pull/31 and https://github.com/ffvvc/FFmpeg/pull/219.

**Comment by frankplow** [comment]
Can you please close this issue @nuomi2021?

**Comment by nuomi2021** [comment]
sure, thank you
