### ISSUE TITLE
Remove unused SAD size

### ISSUE THREAD

**Issue by nuomi2021** [ffvvc/FFmpeg#228]
From Benjamin Bross:
DMVR, I recently saw that also 32x32 to 128x128 AVX2 DMVR SAD functions have been added. Not digged deep into that but I was wondering whether these are even used? In VVC DMVR is only allowed for 8x16, 16x8 and 16x16 blocks

@stone-d-chen, could you double confirm it?
you can assert the size first. Then search the spec to find the correct size.

**Comment by stone-d-chen** [comment]
Hmm I was just basing it off of this paper, and assumed any CU size is valid but I will search the spec... it could be the block type used is by definition already a restricted size? e.g. PUs can only be certain sizes already?
https://ieeexplore.ieee.org/document/9252910

![image](https://github.com/ffvvc/FFmpeg/assets/15571478/9cbd991c-49d7-4a66-9ac1-ef5d4ebebcdc)

**Comment by stone-d-chen** [comment]
But I will double check this

**Comment by nuomi2021** [comment]
dmvr_mv_refine called by derive_sb_mv. I guess subblocks are constrained. you can check the mi->num_sb_x assignment

**Comment by stone-d-chen** [comment]
Hi yeah, seems like I was mistaken, the sub-blocks are constrained pg 235 of the spec
![image](https://github.com/ffvvc/FFmpeg/assets/15571478/5973f830-d703-491c-917b-2b3d1da6c7cb)

I will submit a patch though it will be mostly cosmetic since the .asm uses the same codepaths for 16-128; I should also change the checkasm as well to not test the other block widths.

**Comment by nuomi2021** [comment]
@stone-d-chen, thank you, 

Before you send the patch, could you add:
av_assert0(w == 16 && h == 16  || w == 8 && h == 16 ||  w == 16 && h == 8);
and run a full conformance test to make sure our assumption is correct?
Do not include the assert in your patch, just test it

also, will the height impact your code? it's just two height types 8 and 16

**Comment by stone-d-chen** [comment]
> @stone-d-chen, thank you,
> 
> Before you send the patch, could you add: av_assert0(w == 16 && h == 16 || w == 8 && h == 16 || w == 16 && h == 8); and run a full conformance test to make sure our assumption is correct? Do not include the assert in your patch, just test it

Sounds good  -- can I assume if it doesn't appear in the conformance clips than it will never appear? Or another way - does the conformance clips test all features / constraints of the spec?

> also, will the height impact your code? it's just two height types 8 and 16

The actual asm it doesn't - the height was looped over 1 row at a time already. I think at most there could be additional optimizations given that there's new constraints.

**Comment by nuomi2021** [comment]
> > @stone-d-chen, thank you,
> > Before you send the patch, could you add: av_assert0(w == 16 && h == 16 || w == 8 && h == 16 || w == 16 && h == 8); and run a full conformance test to make sure our assumption is correct? Do not include the assert in your patch, just test it
> 
> Sounds good -- can I assume if it doesn't appear in the conformance clips than it will never appear? Or another way - does the conformance clips test all features / constraints of the spec?
No for both. 
But, Benjamin is an expert on the VVC spec. If he says so and the conformance clip proves it, I guess it's low risk.
> 
> > also, will the height impact your code? it's just two height types 8 and 16
> 
> The actual asm it doesn't - the height was looped over 1 row at a time already. I think at most there could be additional 
Given the new constraints, you can optimize by using as many registers as possible, processing 4 or 8 rows at a time.

Thank you

**Comment by nuomi2021** [comment]
merged as https://github.com/FFmpeg/FFmpeg/commit/d82c5035558730f0d1f2e5aec66df6d0db7f4e6f
thank you stone

**Comment by stone-d-chen** [comment]
Great! Switching focus to deblocking now
