### ISSUE TITLE
change alf step size to 8.

### ISSUE THREAD

**Issue by nuomi2021** [ffvvc/FFmpeg#229]
@QSXW current ALF step size is 4. 
could you help set ALF step size to 8? 
thank you

From  Benjamin Bross:
> for ALF where functions are in increments of 4 while 8 should be sufficient according to the spec.

**Comment by QSXW** [comment]
Yes sure.

**Comment by QSXW** [comment]
Fixed and closed this issue. Please check https://github.com/FFmpeg/FFmpeg/commit/442e94e5e476710dfbb9f611a86ac3c86156394c for more details.
