### ISSUE TITLE
Upstream ALF checkasm random faliure.

### ISSUE THREAD

**Issue by nuomi2021** [ffvvc/FFmpeg#230]
see https://patchwork.ffmpeg.org/project/ffmpeg/patch/OSZP286MB2173887A0BBF4B1B091042F6CAE22@OSZP286MB2173.JPNP286.PROD.OUTLOOK.COM/#85687

**Comment by QSXW** [comment]
Fixed and closed this issue. Please check https://github.com/FFmpeg/FFmpeg/commit/09d3370c2884f4535d738e9baea008738cfb602b for more details.
