### ISSUE TITLE
Multilayer bitstreams support

### ISSUE THREAD

**Issue by birdie-github** [ffvvc/FFmpeg#263]
Sample file:

[basketball_2_layers.zip](https://github.com/user-attachments/files/17190378/basketball_2_layers.zip)

Error: `Decoding of multilayer bitstreams is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.`

**Comment by nuomi2021** [comment]
Hi @birdie-github,

Is this feature a priority? We’re still missing some critical performance optimizations. Would it make sense to delay this until we complete the majority of those optimizations?

Thank you

**Comment by birdie-github** [comment]
> Is this feature a priority?

Absolutely not. I'm not even sure it's worth implementing/pursuing. It's really up to you.
