### ISSUE TITLE
Support crop

### ISSUE THREAD

**Issue by nuomi2021** [ffvvc/FFmpeg#5]
https://github.com/ffvvc/tests/tree/main/conformance/failed/CROP

**Comment by frankplow** [comment]
Since https://github.com/ffmpeg/ffmpeg/commit/c252d2b84a35e10d541f857632bafd9326023e72, both conformance cropping test bitstreams now pass.  I think those few touched lines are all that is needed to support crop, this is all HEVC has also.

**Comment by nuomi2021** [comment]
Thank you, Frank
