### ISSUE TITLE
LTRP_A_ERICSSON failure with assembly optimisations enabled

### ISSUE THREAD

**Issue by frankplow** [ffvvc/FFmpeg#59]
The test LTRP_A_ERICSSON fails when assembly optimisations are enabled. This affects NASM and YASM on both Linux and Windows. This is not a duplicate of #26 - applying patch bab47cad2c2b6d78a17765161a853dd2dcd46775 fixes all valgrind memcheck errors, but the test still fails.

**Comment by nuomi2021** [comment]
thank you for the report. Let me check.

**Comment by nuomi2021** [comment]
fixed, https://github.com/ffvvc/FFmpeg/actions/runs/4658749407
@frankplow , you are right, the green check is pretty.
