### ISSUE TITLE
Intermittent Windows build failure

### ISSUE THREAD

**Issue by frankplow** [ffvvc/FFmpeg#68]
Windows CI build seems to fail randomly with `unable to find mspdbcore.dll`. [Here is an example](https://github.com/ffvvc/FFmpeg/actions/runs/4787027092/jobs/8511712666). Thought this had been fixed by 68c056f071a543c50395515275a6f26e3223df64 but seemingly not.

**Comment by nuomi2021** [comment]
hmm, wried

**Comment by frankplow** [comment]
Potentially fixed by #70. The error is intermittent therefore I am going to leave this issue open for the time-being. Once the CI workflow has run a few more times and the error hasn't cropped up I will close this.

**Comment by nuomi2021** [comment]
@frankplow ,  is it related to memory?
maybe we need limited the build thread number to 4
https://github.com/ffvvc/FFmpeg/actions/runs/4906483018/jobs/8760960018?pr=76#step:7:283

**Comment by frankplow** [comment]
We haven't had a Windows build failure since 492964d2918a1cc7c2b0d8cc4e17497810152035, so I'm going to close this issue.
